### ISSUE TITLE
Tests keep fail

### ISSUE THREAD

**Issue by JonasSValfridsson** [dvalfrid/gastolibro#12]
|| Tests run: 4, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.362 sec <<< FAILURE!
src/test/java/net/valfridsson/gastolibro/jdbi/EntryDaoTest.java|\<findAll\>| 
|| java.lang.AssertionError: 
|| Expecting:
||   <[net.valfridsson.gastolibro.core.Entry@2d480e69,
||     net.valfridsson.gastolibro.core.Entry@878fbb0,
||     net.valfridsson.gastolibro.core.Entry@392096f7,
||     net.valfridsson.gastolibro.core.Entry@b8b803e,
||     net.valfridsson.gastolibro.core.Entry@af0bfa79,
||     net.valfridsson.gastolibro.core.Entry@6cd25058]>
|| to contain only:
||   <[net.valfridsson.gastolibro.core.Entry@b8b803e,
||     net.valfridsson.gastolibro.core.Entry@392096f7,
||     net.valfridsson.gastolibro.core.Entry@878fbb0,
||     net.valfridsson.gastolibro.core.Entry@2d480e69]>
|| but the following elements were unexpected:
||   <[net.valfridsson.gastolibro.core.Entry@af0bfa79,
||     net.valfridsson.gastolibro.core.Entry@6cd25058]>
|| 
|| 	at net.valfridsson.gastolibro.jdbi.EntryDaoTest.findAll(EntryDaoTest.java:32)
|| 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
|| 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
|| 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
|| 	at java.lang.reflect.Method.invoke(Method.java:498)
|| 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
|| 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
|| 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
|| 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
|| 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
|| 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
|| 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
|| 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
|| 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
|| 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
|| 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
|| 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
|| 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
|| 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
|| 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
|| 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
|| 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
|| 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
|| 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
|| 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
|| 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
|| 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
|| 	at java.lang.reflect.Method.invoke(Method.java:498)
|| 	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
|| 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
|| 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
|| 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
|| 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
|| 
src/test/java/net/valfridsson/gastolibro/jdbi/EntryDaoTest.java|\<findX\>| 
|| java.lang.AssertionError: 
|| Expecting:
||   <[net.valfridsson.gastolibro.core.Entry@7be8ba4d,
||     net.valfridsson.gastolibro.core.Entry@ff6ee0d4,
||     net.valfridsson.gastolibro.core.Entry@2559ca1b,
||     net.valfridsson.gastolibro.core.Entry@1d64562,
||     net.valfridsson.gastolibro.core.Entry@856c76e9,
||     net.valfridsson.gastolibro.core.Entry@5c729d70,
||     net.valfridsson.gastolibro.core.Entry@eab01cf7,
||     net.valfridsson.gastolibro.core.Entry@bd1b063e]>
|| to contain only:
||   <[net.valfridsson.gastolibro.core.Entry@7be8ba4d,
||     net.valfridsson.gastolibro.core.Entry@ff6ee0d4]>
|| but the following elements were unexpected:
||   <[net.valfridsson.gastolibro.core.Entry@2559ca1b,
||     net.valfridsson.gastolibro.core.Entry@1d64562,
||     net.valfridsson.gastolibro.core.Entry@856c76e9,
||     net.valfridsson.gastolibro.core.Entry@5c729d70,
||     net.valfridsson.gastolibro.core.Entry@eab01cf7,
||     net.valfridsson.gastolibro.core.Entry@bd1b063e]>
|| 
|| 	at net.valfridsson.gastolibro.jdbi.EntryDaoTest.findX(EntryDaoTest.java:48)
|| 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
|| 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
|| 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
|| 	at java.lang.reflect.Method.invoke(Method.java:498)
|| 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
|| 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
|| 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
|| 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
|| 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
|| 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
|| 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
|| 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
|| 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
|| 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
|| 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
|| 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
|| 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
|| 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
|| 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
|| 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
|| 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
|| 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
|| 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
|| 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
|| 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
|| 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
|| 	at java.lang.reflect.Method.invoke(Method.java:498)
|| 	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
|| 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
|| 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
|| 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
|| 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
|| 
|| 
|| Results :
|| 
src/test/java/net/valfridsson/gastolibro/jdbi/EntryDaoTest.java|\<findAll\>| (..)
||   findX(net.valfridsson.gastolibro.jdbi.EntryDaoTest): (..)
|| 
|| Tests in error: 
||   net.valfridsson.gastolibro.GastolibroApplicationTest: Multiple servlets map to path /*: home[mapped:JAVAX_API:null],io.dropwizard.jersey.setup.JerseyServletContainer-60e9c3a5[mapped:EMBEDDED:null]
|| 
|| Tests run: 7, Failures: 2, Errors: 1, Skipped: 0
||

**Comment by dvalfrid** [comment]
Last commit fixed this.
