### ISSUE TITLE
Multiple Servlets mapping to Root

### ISSUE THREAD

**Issue by JonasSValfridsson** [dvalfrid/gastolibro#13]
INFO  [2017-07-04 18|44| 17,431] org.eclipse.jetty.util.log: Logging initialized @881ms to org.eclipse.jetty.util.log.Slf4jLog
|| 
INFO  [2017-07-04 18|44| 17,476] io.dropwizard.server.SimpleServerFactory: Registering jersey handler with root path prefix: /
|| 
INFO  [2017-07-04 18|44| 17,477] io.dropwizard.server.SimpleServerFactory: Registering admin handler with root path prefix: /admin
|| 
INFO  [2017-07-04 18|44| 17,478] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: home for path /*
|| 
INFO  [2017-07-04 18|44| 17,566] io.dropwizard.server.SimpleServerFactory: Registering jersey handler with root path prefix: /
|| 
INFO  [2017-07-04 18|44| 17,566] io.dropwizard.server.SimpleServerFactory: Registering admin handler with root path prefix: /admin
|| 
INFO  [2017-07-04 18|44| 17,567] io.dropwizard.server.ServerFactory: Starting gastolibro
|| 
INFO  [2017-07-04 18|44| 17,648] org.eclipse.jetty.setuid.SetUIDListener: Opened gastolibro@277b8fa4{HTTP/1.1,[http/1.1]}{0.0.0.0:3000}
|| 
INFO  [2017-07-04 18|44| 17,650] org.eclipse.jetty.server.Server: jetty-9.4.z-SNAPSHOT
|| 
INFO  [2017-07-04 18|44| 17,835] org.eclipse.jetty.server.AbstractConnector: Started gastolibro@277b8fa4{HTTP/1.1,[http/1.1]}{0.0.0.0:3000}
|| 
ERROR [2017-07-04 18|44| 17,837] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
|| ! java.lang.IllegalStateException: Multiple servlets map to path /*: home[mapped:JAVAX_API:null],io.dropwizard.jersey.setup.JerseyServletContainer-5f172d4a[mapped:EMBEDDED:null]
|| ! at org.eclipse.jetty.servlet.ServletHandler.updateMappings(ServletHandler.java:1414)
|| ! at org.eclipse.jetty.servlet.ServletHandler.doStart(ServletHandler.java:156)
|| ! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
|| ! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
|| ! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
|| ! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
|| ! at org.eclipse.jetty.server.handler.ScopedHandler.doStart(ScopedHandler.java:120)
|| ! at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:830)
|| ! at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344)
|| ! at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:799)
|| ! at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
|| ! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
|| ! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
|| ! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
|| ! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
|| ! at com.codahale.metrics.jetty9.InstrumentedHandler.doStart(InstrumentedHandler.java:103)
|| ! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
|| ! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
|| ! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
|| ! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
|| ! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
|| ! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
|| ! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
|| ! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
|| ! at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:290)
|| ! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
|| ! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
|| ! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
|| ! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
|| ! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
|| ! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
|| ! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
|| ! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
|| ! at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:252)
|| ! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
|| ! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
|| ! at org.eclipse.jetty.server.Server.start(Server.java:452)
|| ! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
|| ! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
|| ! at org.eclipse.jetty.server.Server.doStart(Server.java:419)
|| ! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
|| ! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
|| ! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
|| ! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
|| ! at io.dropwizard.cli.Cli.run(Cli.java:74)
|| ! at io.dropwizard.Application.run(Application.java:89)
|| ! at net.valfridsson.gastolibro.GastolibroApplication.main(GastolibroApplication.java:21)
|| 
INFO  [2017-07-04 18|44| 17,846] org.eclipse.jetty.server.AbstractConnector: Stopped gastolibro@277b8fa4{HTTP/1.1,[http/1.1]}{0.0.0.0:3000}
|| 
INFO  [2017-07-04 18|44| 17,846] org.eclipse.jetty.server.handler.ContextHandler: Stopped i.d.j.MutableServletContextHandler@4596f8f3{/,null,UNAVAILABLE}
|| 
|| Multiple servlets map to path /*: home[mapped:JAVAX_API:null],io.dropwizard.jersey.setup.JerseyServletContainer-5f172d4a[mapped:EMBEDDED:null]
|| 
|| [Finished in 4 seconds with code 1]

**Comment by dvalfrid** [comment]
SBS... use the right configuration :)
